catch(logic_error err) {

throw "We have a problem";

}